### ISSUE TITLE
[Session request] Introduction to Docker

### ISSUE THREAD

**Issue by DexterPOSH** [DexterPOSH/IndiaOpsUG#1]
## Session topic
Introduction to Docker

## Level
Beginner

## Background/Skills required
Ops or IT Pro

**Comment by ajeetraina** [comment]
29th July looks good to me.

**Comment by DexterPOSH** [comment]
@ajeetraina Awesome. I will schedule the invite and update the request here.

**Comment by DexterPOSH** [comment]
@ajeetraina I have added the necessary folder structure and a Readme file for the session.
Kindly share the slides and code samples after the session so that attendees get it easily.

**Comment by DexterPOSH** [comment]
Pushed the slides and YouTube link.
